version: "3.7"
services:
  meteor-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    volumes:
      - 'get-real-src:/home/meteor/app'
  meteor-db:
    image: mongo:latest

volumes:
  get-real-src:
